name: Build  then Push to ECR
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: flash-container

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.SECRETKEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      # - name: Set IMAGE_TAG from Git SHA
        # run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set IMAGE_TAG from Git SHA
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            SHORT_SHA=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)
            echo "IMAGE_TAG=$SHORT_SHA" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: docker build -t $ECR_REPOSITORY:$IMAGE_TAG ./docker
  
      - name: Tag and push to ECR
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          echo "Image pushed: ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG"