name: Terraform Apply
on:
  workflow_dispatch:  # Manual trigger

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESSKEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRETKEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.13.3

    - name: Download Plan Artifact from s3
      run: aws s3 cp s3://codechalllengetfstate/tfplan.binary tfplan.binary

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan.binary